version: "3"

services:
  servers:
    build:
      dockerfile: xinetd.Dockerfile
    ports:
      - "5000-5100:5000-5100"
    restart: always

    volumes:
      - ./servers:/code:ro
      - ./xinetd:/etc/xinetd.d:ro
